name: grocerymart
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependency_overrides:
  intl: ^0.17.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.3
  page_transition: ^2.1.0
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.5.1

  flutter_form_builder: ^9.3.0
  form_builder_validators: ^11.0.0


  hive_flutter: ^1.1.0
  dio: ^5.5.0+1

  freezed_annotation: ^2.4.4
  pretty_dio_logger: ^1.4.0
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.4.0
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  scrollable_positioned_list: ^0.3.8
#  geolocator: ^12.0.0
  app_settings: ^5.1.1
  readmore: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  dotted_line: ^3.2.2
#  flutter_stripe: ^11.0.0
  http: ^1.2.2
#  firebase_core: ^2.16.0
  flutter_html: ^3.0.0-beta.2
#  firebase_messaging: ^14.6.9
#  flutter_local_notifications: ^16.1.0
  lite_rolling_switch: ^1.0.1

  intl_utils: ^2.3.0
  intl: ^0.19.0

  device_preview: ^1.2.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  json_annotation: ^4.8.1
  freezed: ^2.4.6

  flutter_localizations:
    sdk: flutter

  pinput: ^5.0.0
  connectivity_wrapper: ^1.1.4
  flutter_cache_manager: ^3.4.0
#  flutter_credit_card: ^4.0.0+1
#  awesome_card: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_gen_runner:

  build_runner:
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/images/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/font/OpenSans-Light.ttf
          weight: 300
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/font/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 700
