// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyD3shCOMDkNdiln9KrCwKKjhuNu5AbPr4Q',
//     appId: '1:579795568119:web:169c5911ff14eb1b48daf2',
//     messagingSenderId: '579795568119',
//     projectId: 'alsultan-bakkerij',
//     authDomain: 'alsultan-bakkerij.firebaseapp.com',
//     storageBucket: 'alsultan-bakkerij.appspot.com',
//     measurementId: 'G-VE3LH2V1CS',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyD4HYWLSv8hJSdkLE2bz89G0teRjv72G1g',
//     appId: '1:579795568119:android:04902e9d6cd5df3f48daf2',
//     messagingSenderId: '579795568119',
//     projectId: 'alsultan-bakkerij',
//     storageBucket: 'alsultan-bakkerij.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBpF8LmMx2pnke4tdnuOwM0PZ5aA-o1JvQ',
//     appId: '1:579795568119:ios:998d882dd702053748daf2',
//     messagingSenderId: '579795568119',
//     projectId: 'alsultan-bakkerij',
//     storageBucket: 'alsultan-bakkerij.appspot.com',
//     iosBundleId: 'com.alsultanbakkerij',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBpF8LmMx2pnke4tdnuOwM0PZ5aA-o1JvQ',
//     appId: '1:579795568119:ios:4979f16e55f1ec0248daf2',
//     messagingSenderId: '579795568119',
//     projectId: 'alsultan-bakkerij',
//     storageBucket: 'alsultan-bakkerij.appspot.com',
//     iosBundleId: 'com.grocerymart',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyD3shCOMDkNdiln9KrCwKKjhuNu5AbPr4Q',
//     appId: '1:579795568119:web:bf8e1d290b46ca4548daf2',
//     messagingSenderId: '579795568119',
//     projectId: 'alsultan-bakkerij',
//     authDomain: 'alsultan-bakkerij.firebaseapp.com',
//     storageBucket: 'alsultan-bakkerij.appspot.com',
//     measurementId: 'G-1HH3ML2FY0',
//   );
// }
